-- Deliberately a no-op on TiDB.
--
-- The former repeatable migration read PostgreSQL-only public.app_documents
-- through PL/pgSQL, JSONB operators, and executable LATERAL queries. A fresh
-- TiDB Cloud database cannot access that PostgreSQL database, and TiDB does
-- not support those server-side constructs. Keep legacy data migration
-- explicit: export the old document store, import it into app_documents using
-- the application import command. Migrate normalized legacy records separately
-- only if that historical data is needed.
--
-- This remains a repeatable migration so Flyway records the compatibility
-- boundary without trying to execute PostgreSQL syntax on every startup.
SELECT 1 AS tidb_document_store_import_skipped;
