FROM node:22-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY src ./src
COPY bin ./bin
COPY db ./db
COPY config ./config
COPY models ./models
COPY data ./data

CMD ["npm", "run", "db:import-files"]
